name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone ChatGPTNextWeb repository
      run: git clone https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd ChatGPT-Next-Web
        yarn install --frozen-lockfile

    - name: Build the ChatGPTNextWeb
      run: |
        cd ChatGPT-Next-Web
        yarn build

    - name: Organize project directories for artifact
      run: |
        cd ChatGPT-Next-Web
        mkdir -p web/_next/
        cp -r public/* web/
        cp -r .next/static web/_next/
        zip -r ../assets/web.zip web/*

    - name: Upload project directories
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: assets/web.zip

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download web.zip
        uses: actions/download-artifact@v4
        with:
          path: ./assets

      - name: Prepare and zip artifacts
        run: |
          echo "Displaying the structure of downloaded files:"
          ls -R ./assets

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter build
        run: |
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
