name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Clone ChatGPTNextWeb repository
      run: git clone https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Node.js and Build
      working-directory: ChatGPT-Next-Web
      run: |
        yarn install --frozen-lockfile
        yarn build

    - name: Organize project directories for artifact
      run: |
        mkdir -p ChatGPT-Next-Web/web/_next/
        cp -r ChatGPT-Next-Web/public/* ChatGPT-Next-Web/web/
        cp -r ChatGPT-Next-Web/.next/static ChatGPT-Next-Web/web/_next/
        rm -rf assets/*
        cd ChatGPT-Next-Web
        zip -r ../assets/web.zip web
        cd ..
        rm -rf ChatGPT-Next-Web

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.1'

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Run Flutter build
      run: |
        flutter build apk --release

    - name: Upload web.zip
      uses: actions/upload-artifact@v4
      with:
        name: web-zip
        path: assets/web.zip

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
